#!/usr/bin/env python

import argparse
import sys

from os import environ
from ring_doorbell import Ring

parser = argparse.ArgumentParser()
parser.add_argument("-t", "--type", help="The type of Ring device to check. [doorbell, chime]")
#parser.add_argument("-n", "--name", help="The name of device to check. If ommitted, check the first device found of the specified type.")
parser.add_argument("-a", "--attr", help="The attribute to check. [battery, wifi]")
args = parser.parse_args()

ring = Ring(environ['RING_EMAIL'], environ['RING_PASSWORD'])

# TODO: allow specification of name, in case you have more
# than one of a given device
if args.type == 'doorbell':
    device = ring.doorbells[0]
elif args.type == 'chime':
    device = ring.chimes[0]

if args.attr == 'battery':
    message = device.name + " has " + str(device.battery_life) + "% battery"

    if device.battery_life < 10:
        print "CRITICAL: " + message
        sys.exit(2)
    elif device.battery_life < 20:
        print "WARNING: " + message
        sys.exit(1)
    else:
        print "OK: " + message
        sys.exit(0)
elif args.attr == 'wifi':
    message = device.name + " has a " + device.wifi_signal_category + " WiFi signal"

    if device.wifi_signal_category == 'good':
        print "OK: " + message
        sys.exit(0)
    else:
        print "CRITICAL: " + message
        sys.exit(2)
